type Padecimiento {
    nombre: String
}
type PoblacionDestino {
    edad_minima: Int!
    edad_maxima: Int!
    sexo: Int!
    padecimientos: [Padecimiento!]
}
type Recomendacion {
    nombre: String
    tipo: String // Vacuna, orientacion, desparasitación
    poblacion_destino: [PoblacionDestino]
}

type Antropometria {
    fecha: DateTime
    peso: Float
    talla: Float
    circunferencia: Float!
}

type Familiar {
    cartila: Cartilla
    parentezco: String
}
type Filiacion {
    institucion: Institucion
    numero: String
    titularidad: String
    vigencia: []
}
type Vacuna {
    nombre: String
    enfermedad: String
    dosis: String
    edad: Int!
}
type Cartilla {
    curp: String
    nombres: String
    apellido1: String
    apellido2: String
    fecha_nacimiento: DateTime
    sexo: Int
    tipo_sangre: String!
    pin: String
    padecimientos: [Padecimiento!]
    familiares: [Familiar!]
}

type CuentaCorreo {
    correo: String
    verificado: bool
}
type Usuario {
    cartilla: Cartilla
    correos: [CuentaCorreo]
    contrasenia: String
}